# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4



trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students(2823c4f9-6890-41ae-b9d7-db9bf898bd06)'
    appType: 'webApp'
    appName: 'chainmates-backend'
    deployToSlotOrASE: true
    resourceGroupName: 'fiit-tp-backend'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students(2823c4f9-6890-41ae-b9d7-db9bf898bd06)'
    appType: 'webApp'
    appName: 'chainmates-backend'
    deployToSlotOrASE: true
    resourceGroupName: 'fiit-tp-backend'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto' 
    appSettings: |
      {
        "Logging": {
          "LogLevel": {
            "Default": "Information",
            "Microsoft.AspNetCore": "Warning"
          }
        },
        "AllowedHosts": "*",
        "Google": {
          "ClientId": "10396760922-6v29co045d1objrtmu07sf6maqpi07lb.apps.googleusercontent.com"
        },
        "Neo4j": {
          "Uri": "neo4j+s://21e39a0e.databases.neo4j.io",
          "Username": "neo4j",
          "Password": "c7s2v93-vxDEshfhmszARlUitQSJuYfquJ2bnM6AFLk"
        }
      }