# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: 'My pool'
  # vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: AzureAppServiceSettings@1
  inputs:
    azureSubscription: 'Azure for Students Starter(982b2a6a-2d15-4a59-950d-65b0a39ea32f)'
    appName: 'backend-tag'
    resourceGroupName: 'backend-tag_group'
    appSettings: |
      {
        "Logging": {
          "LogLevel": {
            "Default": "Information",
            "Microsoft.AspNetCore": "Warning"
          }
        },
        "AllowedHosts": "*",
        "Google": {
          "ClientId": "10396760922-6v29co045d1objrtmu07sf6maqpi07lb.apps.googleusercontent.com"
        },
        "Neo4j": {
          "Uri": "neo4j+s://21e39a0e.databases.neo4j.io",
          "Username": "neo4j",
          "Password": "c7s2v93-vxDEshfhmszARlUitQSJuYfquJ2bnM6AFLk"
        }
      }
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

