networks:
  team07:
    external: true

services:
  presentation-web-backend:
    build: .
    container_name: presentation-web-backend
    image: presentation-web-backend
    restart: unless-stopped
    ports:
      - ${PRESENTATION_BACKEND_HOST_PORT:-7000}:5000
    networks:
      - team07
    volumes:
      - presentation-web-backend_keys:/etc/team07/presentation-web/backend/data-protection-keys
      - ./appsettings.json:/app/appsettings.json:ro

volumes:
  presentation-web-backend_keys:
    name: presentation-web-backend_keys
